apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpuhog
  namespace: lab14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpuhog
  template:
    metadata:
      labels:
        app: cpuhog
    spec:
      nodeSelector:
        kubernetes.io/hostname: labnp-worker
      containers:
        - name: hog
          image: polinux/stress
          command: ["stress"]
          args: ["--cpu", "2", "--timeout", "600"]
          resources:
            requests:
              cpu: "500m"
              memory: "64Mi"
            limits:
              cpu: "1000m"
              memory: "128Mi"
