apiVersion: v1
kind: Namespace
metadata:
  name: week3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memhog-besteffort
  namespace: week3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memhog-besteffort
  template:
    metadata:
      labels:
        app: memhog-besteffort
    spec:
      nodeSelector:
        kubernetes.io/hostname: labnp-worker
      containers:
        - name: hog
          image: polinux/stress
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "2500M", "--vm-hang", "1"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memhog-burstable
  namespace: week3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memhog-burstable
  template:
    metadata:
      labels:
        app: memhog-burstable
    spec:
      nodeSelector:
        kubernetes.io/hostname: labnp-worker
      containers:
        - name: hog
          image: polinux/stress
          command: ["stress"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
          args: ["--vm", "1", "--vm-bytes", "2500M", "--vm-hang", "1"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memhog-guaranteed
  namespace: week3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memhog-guaranteed
  template:
    metadata:
      labels:
        app: memhog-guaranteed
    spec:
      nodeSelector:
        kubernetes.io/hostname: labnp-worker
      containers:
        - name: hog
          image: polinux/stress
          command: ["stress"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          args: ["--vm", "1", "--vm-bytes", "1500M", "--vm-hang", "1"]
